/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { Context, Env } from 'hono';

import { PetsListParams,
Pet,
StoresListParams } from './petstore.schemas';

export type PetsListContext<E extends Env = any> = Context<E, '/pets', { in: { query: PetsListParams, }, out: { query: PetsListParams, } }>
export type PetsCreateContext<E extends Env = any> = Context<E, '/pets', { in: { json: Pet, }, out: { json: Pet, } }>
export type PetsReadContext<E extends Env = any> = Context<E, '/pets/:id', { in: { param: {
 id: string,
 }, }, out: { param: {
 id: string,
 }, } }>
export type StoresListContext<E extends Env = any> = Context<E, '/stores', { in: { query: StoresListParams, }, out: { query: StoresListParams, } }>
export type StoresReadContext<E extends Env = any> = Context<E, '/stores/:id', { in: { param: {
 id: string,
 }, }, out: { param: {
 id: string,
 }, } }>