/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
export type StoresListParams = {
filter: string;
};

export type PetsListParams = {
filter: string;
};

export interface Store {
  address: Address;
  name: string;
}

export interface Pet {
  age: number;
  name: string;
}

export interface Address {
  city: string;
  street: string;
}

