/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from 'zod';

export const petsListQueryParams = zod.object({
  "filter": zod.string()
})

export const petsListResponseItem = zod.object({
  "name": zod.string(),
  "age": zod.number()
}).strict()
export const petsListResponse = zod.array(petsListResponseItem)


export const petsCreateBody = zod.object({
  "name": zod.string(),
  "age": zod.number()
})

export const petsCreateResponse = zod.object({
  "name": zod.string(),
  "age": zod.number()
}).strict()


export const petsReadParams = zod.object({
  "id": zod.string()
})

export const petsReadResponse = zod.object({
  "name": zod.string(),
  "age": zod.number()
}).strict()


export const storesListQueryParams = zod.object({
  "filter": zod.string()
})

export const storesListResponseItem = zod.object({
  "name": zod.string(),
  "address": zod.object({
  "street": zod.string(),
  "city": zod.string()
}).strict()
}).strict()
export const storesListResponse = zod.array(storesListResponseItem)


export const storesReadParams = zod.object({
  "id": zod.string()
})

export const storesReadResponse = zod.object({
  "name": zod.string(),
  "address": zod.object({
  "street": zod.string(),
  "city": zod.string()
}).strict()
}).strict()

