/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import {
  Hono
} from 'hono'

import { petsListHandlers } from './handlers/petsList';
import { petsCreateHandlers } from './handlers/petsCreate';
import { petsReadHandlers } from './handlers/petsRead';
import { storesListHandlers } from './handlers/storesList';
import { storesReadHandlers } from './handlers/storesRead';


const app = new Hono()


app.get('/pets',...petsListHandlers)



app.post('/pets',...petsCreateHandlers)



app.get('/pets/:id',...petsReadHandlers)



app.get('/stores',...storesListHandlers)



app.get('/stores/:id',...storesReadHandlers)


export default app