/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * TypeSpec Orval API
 * OpenAPI spec version: 0.0.0
 */
export type PostsUpdatePost200 = {
  post: Post;
};

export type PostsUpdatePostBody = {
  post?: PostUpdate;
};

export type PostsCreatePost200 = {
  post: Post;
};

export type PostsCreatePostBody = {
  post: Post;
};

export type PostsGetPosts200 = {
  posts: Post[];
};

export type HelloHello200 = {
  message: string;
};

export interface PostUpdate {
  post_content?: string;
  post_title?: string;
  post_uuid?: string;
}

export interface Post {
  post_content: string;
  post_title: string;
  post_uuid: string;
}

export interface Error {
  message: string;
}

