/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * TypeSpec Orval API
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from 'zod';

export const helloHelloResponse = zod.object({
  "message": zod.string()
}).strict()


export const usersGetUsersResponse = zod.object({
  "users": zod.array(zod.object({
  "user_uuid": zod.string(),
  "user_name": zod.string()
}).strict())
}).strict()


export const usersCreateUserBody = zod.object({
  "user": zod.object({
  "user_uuid": zod.string(),
  "user_name": zod.string()
})
})

export const usersCreateUserResponse = zod.object({
  "user": zod.object({
  "user_uuid": zod.string(),
  "user_name": zod.string()
}).strict()
}).strict()


export const usersUpdateUserBody = zod.object({
  "user": zod.object({
  "user_uuid": zod.string().optional(),
  "user_name": zod.string().optional()
}).optional()
})

export const usersUpdateUserResponse = zod.object({
  "user": zod.object({
  "user_uuid": zod.string(),
  "user_name": zod.string()
}).strict()
}).strict()

