/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * TypeSpec Orval API
 * OpenAPI spec version: 0.0.0
 */
export type UsersUpdateUser200 = {
  user: User;
};

export type UsersUpdateUserBody = {
  user?: UserUpdate;
};

export type UsersCreateUser200 = {
  user: User;
};

export type UsersCreateUserBody = {
  user: User;
};

export type UsersGetUsers200 = {
  users: User[];
};

export type HelloHello200 = {
  message: string;
};

export interface UserUpdate {
  user_name?: string;
  user_uuid?: string;
}

export interface User {
  user_name: string;
  user_uuid: string;
}

export interface Error {
  message: string;
}

