/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * TypeSpec Orval API
 * OpenAPI spec version: 0.0.0
 */
import type { Context, Env } from 'hono';

import { UsersCreateUserBody,
UsersUpdateUserBody } from './tyorapi.schemas';

export type HelloHelloContext<E extends Env = any> = Context<E, '/'>
export type UsersGetUsersContext<E extends Env = any> = Context<E, '/users'>
export type UsersCreateUserContext<E extends Env = any> = Context<E, '/users', { in: { json: UsersCreateUserBody, }, out: { json: UsersCreateUserBody, } }>
export type UsersUpdateUserContext<E extends Env = any> = Context<E, '/users', { in: { json: UsersUpdateUserBody, }, out: { json: UsersUpdateUserBody, } }>