/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * TypeSpec Orval API
 * OpenAPI spec version: 0.0.0
 */
import type { Context, Env } from 'hono';

import { PostsCreatePostBody,
PostsUpdatePostBody } from './tyorapi.schemas';

export type HelloHelloContext<E extends Env = any> = Context<E, '/'>
export type PostsGetPostsContext<E extends Env = any> = Context<E, '/posts'>
export type PostsCreatePostContext<E extends Env = any> = Context<E, '/posts', { in: { json: PostsCreatePostBody, }, out: { json: PostsCreatePostBody, } }>
export type PostsUpdatePostContext<E extends Env = any> = Context<E, '/posts', { in: { json: PostsUpdatePostBody, }, out: { json: PostsUpdatePostBody, } }>