openapi: 3.0.0
info:
  title: TypeSpec Orval API
  version: 0.0.0
tags: []
paths:
  /:
    get:
      operationId: Hello_hello
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /posts:
    get:
      operationId: Posts_getPosts
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  posts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Post'
                required:
                  - posts
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      operationId: Posts_createPost
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  post:
                    $ref: '#/components/schemas/Post'
                required:
                  - post
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                post:
                  type: object
                  required:
                    - post_title
                    - post_content
                  properties:
                    post_title:
                      type: string
                    post_content:
                      type: string
                  description: The template for omitting properties.
              required:
                - post
    put:
      operationId: Posts_updatePost
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  post:
                    $ref: '#/components/schemas/Post'
                required:
                  - post
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                post:
                  $ref: '#/components/schemas/Post'
              required:
                - post
components:
  schemas:
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    Post:
      type: object
      required:
        - post_uuid
        - post_title
        - post_content
      properties:
        post_uuid:
          type: string
        post_title:
          type: string
        post_content:
          type: string
servers:
  - url: http://localhost:3777
    description: production
    variables: {}
