/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * TypeSpec Orval API
 * OpenAPI spec version: 0.0.0
 */
import type { User } from './user';

export type UsersUpdateUser200 = {
  user: User;
};
