/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * TypeSpec Orval API
 * OpenAPI spec version: 0.0.0
 */
import type { PostUpdate } from './postUpdate';

export type PostsUpdatePostBody = {
  post?: PostUpdate;
};
