/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * TypeSpec Orval API
 * OpenAPI spec version: 0.0.0
 */

export interface PostUpdate {
  post_content?: string;
  post_title?: string;
  post_uuid?: string;
}
