/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * TypeSpec Orval API
 * OpenAPI spec version: 0.0.0
 */

/**
 * The template for omitting properties.
 */
export type PostsCreatePostBodyPost = {
  post_content: string;
  post_title: string;
};
